framework:
    messenger:
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        # default_bus: messenger.bus.default

        # buses:
        #     messenger.bus.default: []

        routing:
            # --- TAMBIÉN COMENTAMOS ESTO ---
            # Estas líneas intentan usar el transporte 'async' que acabamos de desactivar.
            # Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            # Symfony\Component\Notifier\Message\ChatMessage: async
            # Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async